version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: modulo_consultas
    environment:
      MYSQL_DATABASE: modulo_consultas
      MYSQL_USER: admin
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
